### ISSUE TITLE
would you share your data?

### ISSUE THREAD

**Issue by xuruochen** [andreiolariu/kaggle-driver-telematics#1]
becauese dataset has been removed ,i have no data of this competition.if you share your data with me,i will appreciate for you ,and i m a new,i got your code and data just to academic research .thank you very much.

**Comment by andreiolariu** [comment]
Hi. I no longer have the data. Deleted it right after the competition ended. Later found out the organizers removed it as well. Sorry I can't help you.

**Comment by alexandrudaia** [comment]
@xuruochen  I have  the data   , I  could share    with you  if  interested  drop me your  email
