### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Sognineibicchieri** [andreiolariu/kaggle-driver-telematics#3]
Dear andreiola，

Thanks a lot for sharing your code and experience in this contest. I am at the moment studying the driving behaviour area and unfortunately axa has deleted the data for this contest. Do you happen to have the full dataset that you can share?

Many thanks again and look forward to your kind feedback,
lily

**Comment by andreiolariu** [comment]
Hi Lily,

I'm sorry, I no longer have the data.
